name: Create OpenVSX release

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Version Tag'
        required: true

permissions:
  contents: write

jobs:
  release:
    name: Release ${{ github.event.inputs.tags }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - run: npm install
        
      - name: Install OpenVSX
        run: npm install ovsx -g
        
      - name: Build Extension
        run: npm run build
      
      - name: Publish Release to OpenVSX.org
        run: |
          npx ovsx publish -p ${{ secrets.ECLIPSE_PAT }}
