name: Create release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Prerelease'    
        required: true
        default: 'true'
      tags:
        description: 'Version Tag'
        required: true

permissions:
  contents: write

jobs:
  release:
    name: Release ${{ github.event.inputs.tags }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - run: npm install
        
      - name: Install VSCE
        run: npm install @vscode/vsce -g
        
      - name: Build Extension
        run: npm run build
      
      # Prerelease flow
      - name: Build Prerelease VSIX package
        if: ${{ github.event.inputs.prerelease == 'true' }}
        run: |
          vsce package --pre-release -o rde-urdf-${{ github.event.inputs.tags }}-pre.vsix
      
      - name: Publish Prerelease to Marketplace
        if: ${{ github.event.inputs.prerelease == 'true' }}
        run: |
          vsce publish --pre-release -p ${{ secrets.VSCE_PAT }}
      
      - name: Create GitHub Prerelease
        if: ${{ github.event.inputs.prerelease == 'true'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "${{ github.event.inputs.tags }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="Prerelease ${{ github.event.inputs.tags }}" \
              --generate-notes \
              --prerelease \
              rde-urdf-${{ github.event.inputs.tags }}-pre.vsix
      
      # Release flow
      - name: Build Release VSIX package
        if: ${{ github.event.inputs.prerelease == 'false' }}
        run: |
          vsce package -o rde-urdf-${{ github.event.inputs.tags }}.vsix
      
      - name: Publish Release to Marketplace
        if: ${{ github.event.inputs.prerelease == 'false' }}
        run: |
          vsce publish -p ${{ secrets.VSCE_PAT }}
      
      - name: Create GitHub Release
        if: ${{ github.event.inputs.prerelease == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "${{ github.event.inputs.tags }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="Release ${{ github.event.inputs.tags }}" \
              --generate-notes \
              rde-urdf-${{ github.event.inputs.tags }}.vsix
